#define LOGIN_OFFICER 1
#define LOGIN_SUCCESS 2
#define LOGIN_FAILED 3
#define LOGOUT_REQUEST 4
#define LOGOUT_SUCCESS 5
#define LOGOUT_FAILED 6
#define CHECK_TICKET 7
#define CHECK_SUCCESS 8
#define CHECK_FAILED 9
#define CHECK_LUGGAGE 10
#define PAYMENT_DONE 11
#define PAYMENT_CANCELED 12

//state
#define AUTHENTICATED 100
#define NON_AUTHENTICATED 101
#define CHECKING 102